### ISSUE TITLE
Sorting by author returns an error

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#46] opened 2015-11-18 16:02 UTC
RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>0,'params'=>{'f.keyword_ssim.facet.limit'=>'11','f.semester_ssi.facet.limit'=>'11','facet.field'=>['committee_member_name_ssim','degree_name_ssi','keyword_ssim','last_name_ssi','program_name_ssi','semester_ssi','year_isi'],'qt'=>'search','f.degree_name_ssi.facet.limit'=>'11','fq'=>'{!raw f=committee_member_name_ssim}Edgar P. Yoder','sort'=>'last_name_ssi asc, title_sort asc','rows'=>'10','f.last_name_ssi.facet.limit'=>'11','f.program_name_ssi.facet.limit'=>'11','f.committee_member_name_ssim.facet.limit'=>'11','f.year_isi.facet.limit'=>'11','wt'=>'ruby','facet'=>'true'}},'error'=>{'msg'=>'sort param field can\'t be found: title_sort','code'=>400}}

**Comment by awead** [comment] 2015-11-18 16:06
this is fixed in #44

**Comment by cam156** [comment] 2015-11-18 16:37
@awead I do not see any changes to the sort fields in #44.  I do not see how it can fix the typos in these lines: https://github.com/psu-stewardship/etda/blob/blacklight/app/controllers/catalog_controller.rb#L146-L147

**Comment by awead** [comment] 2015-11-18 16:58
sorry, I misread that as searching by author.

**Comment by awead** [comment] 2015-11-18 16:59
Looks like the problem is `title_sort` needs to be changed to `title_ssi`

**Closed** 2015-11-20 17:06 UTC
